// Mocks generated by Mockito 5.0.16 from annotations
// in finfacil_app/test/modules/login/domain/usecases/user_validate_usecase_test.dart.
// Do not manually edit this file.

import 'package:finfacil_app/modules/login/domain/repositories/user_validate_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserValidateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserValidateRepository extends _i1.Mock
    implements _i2.UserValidateRepository {
  MockUserValidateRepository() {
    _i1.throwOnMissingStub(this);
  }
}
